# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: Jameslo599/ohms-electrical-ce
  branch: master
  identity_url: https://auth.decapbridge.com/sites/7e78a5c8-353d-4339-9dba-3c9022600406
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Keep this to allow you to edit the cms locally
local_backend: true

# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://scontent-hou1-1.xx.fbcdn.net/v/t39.30808-6/481454401_1188392459659811_1013520013419997181_n.webp?_nc_cat=102&ccb=1-7&_nc_sid=cc71e4&_nc_ohc=0IQX1YsdbJQQ7kNvwGhTysu&_nc_oc=Adkz1wePAAxcSOtc9SJMdhdTdnf0hPjuquURItSEKJAlcbU169wLcVVXO0Rsnd5bO0A&_nc_zt=23&_nc_ht=scontent-hou1-1.xx&_nc_gid=I67UWdjheYqTO1xQSjd7Nw&oh=00_AfYigNIaUTT-RwnPJ2WNP9crND2kqz-rvc-fv5sD788lbg&oe=68DA9420

# Add site links in DecapCMS (optional)
site_url: https://ohms-ce.netlify.app

# Image folders
media_folder: 'src/assets/images/blog'
public_folder: '/assets/images/blog'

# Decap CMS Collections
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'URL Slug',
          name: 'url',
          widget: 'string',
          hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
        }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Image Caption', name: 'imageAlt', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
